### ISSUE TITLE
Implementation correctness, questions

### ISSUE THREAD

**Issue by maltoe** [antirez/redlock-rb#3]
Hello @antirez,

Abusing this issue for some questions regarding the algorithm and the implementation:

 * In the [algorithm description](http://redis.io/topics/distlock) it says, if locking failed, the client ' will try to unlock all the instances (even the instances it believe it was not able to lock).' What's the benefit of that? Only to handle the case that Redis accidentally returned `false` even though it has set the key?
 * Same place: What would you consider a good formula for the Redis timeout given a TTL? Something like 10%? Or sth like `min(200, max(50, ttl/10))` to have hard limits in the lower milliseconds? Also, would you think that the algorithm should abort trying to acquire the locks if the maximum validity time is already used up after the first servers failed to set the lock? Default timeout for the Ruby redis gem is [5 seconds](https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L14), btw. Seems much too long for redlock, given that people will probably specify TTLs in the 0.5 - 2 seconds range.
 * Lbnl, could you add licensing terms to this repository, so that [leandromoreira/redlock-rb](https://github.com/) is ok?

Thanks
Malte

**Comment by antirez** [comment]
Hey @maltoe 

1. Because maybe the command was received by the server. You can avoid unlocking an instance if you never *ever* tried to send the command at all. The concern of this sentence is about instances we tried to contact but we failed to.
2. 10% seems to high, if you want to lock for 5 seconds and you wait 0.5 seconds to lock the majority of 5 instances, too little remaining time is left. I think it makes sense to have things like, ~two order of magnitude smaller. For example 5000 milliseconds lock with 20 milliseconds timeouts. 5 seconds of default timeout for this application is, indeed, not good at all :-) So the default should be overridden.
3. Sorry, missing license? Adding it right now.

**Comment by maltoe** [comment]
Thanks a lot!

**Comment by antirez** [comment]
You are welcome, sorry I forgot to reply to one of your questions: yes, if while trying to lock the elapsed time is already >= (LOCK_TTL - A_FEW_MS) it's a good idea to abort ASAP.

**Comment by antirez** [comment]
@maltoe I see you are contributing to a fork of this lib, I guess what you are developing is more an usable lib compared to my proof of concept, right? Is it a good idea to link it from the Redlock page? Thanks.

**Comment by maltoe** [comment]
@antirez It's your code converted into a gem for easy distribution, started by @leandromoreira. Yes, I think it's a good idea to add the link.

**Comment by antirez** [comment]
Thanks @maltoe , link added.
